name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: iOS
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: xcodebuild test -scheme MilestonesCore -destination platform="iOS Simulator,name=iPhone 11 Pro Max,OS=14.2"
